// 03_prototype/vue-refactor/frontend/src/components/atoms/labels/Badge.vue
<template>
  <div
    :class="[
      variantStyles[variant] ?? variantStyles['badge-primary'],
      shapeStyles[shape] ?? shapeStyles['square'],
      'inline-flex items-center gap-1 text-[9px] p-1',
    ]"
    @click="badgeClicked"
  >
    {{ text }}
  </div>
</template>

<script setup lang="ts">
import type { BadgeVariantType, BadgeShapeType } from "@/domain/types/atomsType"

type Props = {
  text?: string
  shape?: BadgeShapeType
  variant?: BadgeVariantType
}

const props = defineProps<Props>()

const emit = defineEmits(["badge-clicked"])

const badgeClicked = () => {
    emit("badge-clicked", props.text)
}

const variantStyles: Record<BadgeVariantType, string> = {
  "badge-primary": "bg-primary text-white border-[1px] border-primary",
  "badge-secondary": "bg-secondary text-white border-[1px] border-secondary",
  "badge-danger": "bg-danger text-white border-[1px] border-danger",
  "badge-warning": "bg-warning text-white border-[1px] border-warning",
  "badge-success": "bg-success text-white border-[1px] border-success",
  "badge-dark": "bg-gray-30 text-white border-[1px] border-gray-30",
}

const shapeStyles: Record<BadgeShapeType, string> = {
  square: "",
  round: "rounded-xs",
  circle: "rounded-full",
}

const text = props.text ?? ""
const shape = props.shape ?? "square"
const variant = props.variant ?? "badge-primary"
</script>

// 03_プロトタイプ/deckgl/src/components/atoms/labels/Badge.tsx
import React from "react"
import type { BadgeVariantType } from "@/domain/types/atomsType"

type BadgeProps = {
  text?: string // バッジテキスト
  shape?: string //バッジの形状を文字列で指定 square circle
  variant: BadgeVariantType // バッジのスタイル badge-primary, badge-secondary, badge-danger, badge-warning, badge-success のいずれかを指定
}

const Badge: React.FC<BadgeProps> = ({ text, shape, variant }: BadgeProps) => {
  // バッジのスタイルの種類 デフォルトは primary
  let badgeVariant = "bg-primary text-white border-[1px] border-primary"

  if (variant === "badge-secondary") {
    //variantがsecondaryのとき
    badgeVariant =
      "bg-white text-primary border-[1px] border-primary shadow-[inset_0_0_0_1px_var(--primary-color)]" // primary の色を使用
  } else if (variant === "badge-danger") {
    //variantがdangerのとき
    badgeVariant = "bg-danger text-white border-[1px] border-danger"
  } else if (variant === "badge-warning") {
    //variantがwarningのとき
    badgeVariant = "bg-warning text-white border-[1px] border-warning"
  } else if (variant === "badge-success") {
    //variantがsuccessのとき
    badgeVariant = "bg-success text-white border-[1px] border-success"
  } else if (variant === "badge-dark") {
    //variantがsuccessのとき
    badgeVariant = "bg-gray-30 text-white border-[1px] border-gray-30"
  }

  //バッジの形状の種類　circle square
  let cornerShape = "rounded"

  if (shape === "square") {
    cornerShape = "" //四角形の場合は角丸を指定しない
  } else if (shape === "circle") {
    cornerShape = "rounded-full" //円形の場合は角丸をfullにする
  }

  return (
    <div
      className={`${badgeVariant} ${cornerShape} inline-flex items-center gap-1 text-[10px] px-[4px] py-[3px]`} // flex と items-center を追加
    >
      {text}
    </div>
  )
}

export default Badge
