// 03_prototype/SPECTRA_CHAT/frontend/src/components/organisms/homeSite/ui/HomeSiteMain.tsx
"use client"
import React from "react"
import MapApp from "@/components/organisms/homeSite/ui/map/MapApp"
import HeaderApp from "@/components/organisms/homeSite/ui/HeaderApp"
import DialogApp from "@/components/organisms/homeSite/ui/menu/DialogApp"
import LayerControlApp from "@/components/organisms/homeSite/ui/menu/LayerControlApp"

const HomeSite: React.FC = () => {
  return (
    <div>
      <HeaderApp />
      <DialogApp />
      <LayerControlApp />
      <MapApp />
    </div>
  )
}

export default HomeSite

// 03_prototype/vue-refactor/frontend/src/components/organisms/homeSite/ui/HomeSiteMain.vue
<template>
  <Header />
  <ChatPanelApp />
  <MapApp />
</template>
<script setup lang="ts">
import MapApp from "@/components/organisms/homeSite/ui/map/MapApp.vue"
import Header from "@/components/molecules/header/Header.vue"
import ChatPanelApp from "@/components/organisms/homeSite/ui/panel/ChatPanelApp.vue"
</script>
