// 03_prototype/vue-refactor/frontend/src/components/organisms/homeSite/ui/HomeSiteMain.vue
<template>
  <Header />
  <ChatPanelApp />
  <MapApp />
</template>
<script setup lang="ts">
import MapApp from "@/components/organisms/homeSite/ui/map/MapApp.vue"
import Header from "@/components/molecules/header/Header.vue"
import ChatPanelApp from "@/components/organisms/homeSite/ui/panel/ChatPanelApp.vue"
</script>

// 02_src/SPECTRA_CHAT/frontend/src/components/organisms/homeSite/ui/HomeSiteMain.tsx
"use client"
import React from "react"
import MapApp from "@/components/organisms/homeSite/ui/MapApp"
import HeaderApp from "@/components/organisms/homeSite/ui/HeaderApp"
import DialogApp from "@/components/organisms/homeSite/ui/DialogApp"

const HomeSite: React.FC = () => {
  return (
    <div>
      <HeaderApp />
      <DialogApp />
      <MapApp />
    </div>
  )
}

export default HomeSite
