// 03_プロトタイプ/postgis/frontend/src/components/atoms/inputs/Textarea.tsx
type TextareaProps = {
  placeholder?: string
  rows: number
  width?: string
  shape?: string
  isShadow?: boolean
  value: string | null
  className?: string
  isBorderNone?: boolean
  onChange?: (e: React.ChangeEvent<HTMLTextAreaElement>) => void
}

const Textarea: React.FC<TextareaProps> = ({
  placeholder,
  rows,
  width,
  shape,
  isShadow,
  value,
  className,
  isBorderNone,
  onChange,
}) => {
  // 角の形
  let cornerShape = "rounded-md"
  if (shape === "square") {
    cornerShape = ""
  } else if (shape === "rounded-lg") {
    cornerShape = "rounded-lg"
  }

  // 影の有無
  let shadow = ""
  if (isShadow) {
    shadow = "shadow-sm shadow-gray-20"
  }
  let border = "border border-black"
  if (isBorderNone) {
    border = "border-none focus:outline-none"
  }

  // 幅
  const textareaWidth = width ? width : "w-full"
  let fontSize = "md:text-base text-xs"

  return (
    <div className="relative">
      <textarea
        className={`${textareaWidth} ${className} p-2 ${border} resize-none ${cornerShape} ${shadow} ${fontSize}`}
        placeholder={placeholder}
        value={value ? value : ""}
        onChange={onChange}
        rows={rows}
      />
    </div>
  )
}

export default Textarea

// 02_src/SPECTRA_CHAT/frontend/src/presentation/atoms/inputs/Textarea.vue
<template>
  <textarea
    :class="textareaClass"
    :placeholder="placeholder"
    :rows="rows"
    :value="value ?? ''"
    @input="onChangeInput"
  />
</template>
<script setup lang="ts">
import type { TextareaShapeType } from "@/domain/types/atomsType"
import { computed } from "vue"

type Props = {
  placeholder?: string
  rows: number
  shape?: TextareaShapeType
  value: string | null
}

const props = withDefaults(defineProps<Props>(), {
  shape: "round",
  isShadow: false,
  isBorder: false,
  value: "",
})

const emit = defineEmits(['on-change-input'])

const shapeStyles: Record<TextareaShapeType, string> = {
  square: "",
  round: "rounded-md",
}

const textareaClass = computed(() => {
  const cornerShape = shapeStyles[props.shape] ?? shapeStyles.round
  const fontSize = "text-base"
  return `w-full text-black p-2 resize-none border border-gray-80 placeholder:text-sm placeholder:text-gray-70 ${cornerShape} ${fontSize}`
})

const onChangeInput = (e: Event) => {
  emit("on-change-input", (e.target as HTMLTextAreaElement).value)
}
</script>
