// 03_prototype/spectra_chat_nextjs/frontend/src/components/atoms/inputs/Textarea.tsx
import type { TextareaShapeType } from "@/domain/types/atomsType"

type TextareaProps = {
  placeholder?: string
  rows: number
  width?: string
  shape?: TextareaShapeType
  isShadow?: boolean
  value: string | null
  isBorder?: boolean
  onChange: (e: React.ChangeEvent<HTMLTextAreaElement>) => void
}

const shapeStyles: Record<TextareaShapeType, string> = {
  square: "",
  round: "rounded-md",
}

const Textarea: React.FC<TextareaProps> = ({
  placeholder,
  rows,
  shape = "round",
  isShadow = false,
  value,
  isBorder = false,
  onChange,
}) => {
  const cornerShape = shapeStyles[shape] ?? shapeStyles["round"]
  const shadow = isShadow ? "shadow-sm shadow-gray-20" : ""
  const border = isBorder ? "border border-gray-60" : "border-none focus:outline-none"
  const fontSize = "md:text-base text-xs"

  return (
    <textarea
      className={`w-full text-black p-2 ${border} resize-none ${cornerShape} ${shadow} ${fontSize}`}
      placeholder={placeholder}
      value={value ?? ""}
      onChange={onChange}
      rows={rows}
    />
  )
}

export default Textarea

// 02_src/SPECTRA_CHAT/frontend/src/presentation/atoms/inputs/Textarea.vue
<template>
  <textarea
    :class="textareaClass"
    :placeholder="placeholder"
    :rows="rows"
    :value="value ?? ''"
    @input="onChangeInput"
  />
</template>
<script setup lang="ts">
import type { TextareaShapeType } from "@/domain/types/atomsType"
import { computed } from "vue"

type Props = {
  placeholder?: string
  rows: number
  shape?: TextareaShapeType
  value: string | null
}

const props = withDefaults(defineProps<Props>(), {
  shape: "round",
  isShadow: false,
  isBorder: false,
  value: "",
})

const emit = defineEmits(['on-change-input'])

const shapeStyles: Record<TextareaShapeType, string> = {
  square: "",
  round: "rounded-md",
}

const textareaClass = computed(() => {
  const cornerShape = shapeStyles[props.shape] ?? shapeStyles.round
  const fontSize = "text-base"
  return `w-full text-black p-2 resize-none border border-gray-80 placeholder:text-sm placeholder:text-gray-70 ${cornerShape} ${fontSize}`
})

const onChangeInput = (e: Event) => {
  emit("on-change-input", (e.target as HTMLTextAreaElement).value)
}
</script>
