// 02_src/NozawaOpenDataProject/src/components/atoms/buttons/PullTab.tsx
import React from "react"
import type {
  PullTabPositionType,
  PullTabSizeType,
  PullTabVariantType,
} from "@/domain/types/atomsType"

type PullTabProps = {
  position: PullTabPositionType
  icon?: string // アイコンの名前を文字列で指定
  isShadow?: boolean //影をつけるかつけないか
  size: PullTabSizeType // mini、small、normal、large のいずれかを指定
  variant: PullTabVariantType // ボタンのスタイル pullTab-primary, pullTab-secondary, pullTab-danger, pullTab-warning, pullTab-success のいずれかを指定
  onClick: () => void
}

const PullTab: React.FC<PullTabProps> = ({
  position,
  size,
  variant,
  icon,
  isShadow,
  onClick,
}: PullTabProps) => {
  // サイズの種類　small normal largeから指定 paddingSize を動的に設定
  let paddingSize = "p-4" // デフォルトの padding

  if (size === "mini") {
    paddingSize = "p-0" // mini サイズの padding
  } else if (size === "small") {
    paddingSize = "p-2" // small サイズの padding
  } else if (size === "large") {
    paddingSize = "p-6" // large サイズの padding
  }

  // ボタンのスタイルの種類 デフォルトは primary
  let pullTabVariant = "bg-primary text-white hover:bg-primaryDark"

  if (variant === "pullTab-secondary") {
    //variantがsecondaryのとき
    pullTabVariant =
      "bg-white text-primary border-2 border-primary shadow-[inset_0_0_0_2px_var(--primary-color)]" // primary の色を使用、ボーダーの太さも考慮
  } else if (variant === "pullTab-danger") {
    //variantがdangerのとき
    pullTabVariant = "bg-danger text-white"
  } else if (variant === "pullTab-warning") {
    //variantがwarningのとき
    pullTabVariant = "bg-warning text-white"
  } else if (variant === "pullTab-success") {
    //variantがsuccessのとき
    pullTabVariant = "bg-success text-white"
  } else if (variant === "pullTab-dark") {
    //variantがdarkのとき
    pullTabVariant = "bg-gray-20 text-white"
  } else if (variant === "pullTab-light") {
    //variantがlightのとき
    pullTabVariant = "bg-white text-gray-20"
  }
  //ボタンの場所の種類
  let cornerShape = ""

  if (position === "left") {
    cornerShape = "rounded-r-lg py-2"
  } else if (position === "right") {
    cornerShape = "rounded-l-lg py-2"
  } else if (position === "top") {
    cornerShape = "rounded-b-lg px-2"
  } else if (position === "bottom") {
    cornerShape = "rounded-t-lg px-2"
  }

  let buttonShadow = ""
  if (isShadow === true) {
    buttonShadow = "shadow-sm shadow-black"
  }

  return (
    <button
      className={`${paddingSize} ${pullTabVariant} ${cornerShape} ${buttonShadow} flex items-center`} // flex と items-center を追加
      onClick={onClick}
    >
      {icon && <span className="material-icons">{icon}</span>} {/* アイコンを表示*/}
    </button>
  )
}

export default PullTab

// 03_prototype/vue-refactor/frontend/src/components/atoms/buttons/PullTab.vue
<template>
  <button
    :class="[
      paddingClasses,
      variantClasses,
      shapeClasses,
      shadowClass,
      'flex items-center justify-center'
    ]"
    @click="onClick"
  >
    <span v-if="icon" class="material-icons">{{ icon }}</span>
  </button>
</template>

<script lang="ts" setup>
import { computed } from "vue"

type PullTabPositionType = "left" | "right" | "top" | "bottom"
type PullTabSizeType = "mini" | "small" | "normal" | "large"
type PullTabVariantType =
  | "pullTab-primary"
  | "pullTab-secondary"
  | "pullTab-danger"
  | "pullTab-warning"
  | "pullTab-success"
  | "pullTab-dark"
  | "pullTab-light"

interface Props {
  position: PullTabPositionType
  icon?: string
  isShadow?: boolean
  size?: PullTabSizeType
  variant?: PullTabVariantType
  onClick?: () => void
}

const props = defineProps<Props>()

// --- 各スタイル定義 ---
const variantStyles: Record<PullTabVariantType, string> = {
  "pullTab-primary": "bg-primary text-white hover:bg-primaryDark",
  "pullTab-secondary":
    "bg-white text-primary border-2 border-primary shadow-[inset_0_0_0_2px_var(--color-primary)]",
  "pullTab-danger": "bg-danger text-white",
  "pullTab-warning": "bg-warning text-white",
  "pullTab-success": "bg-success text-white",
  "pullTab-dark": "bg-gray-20 text-white",
  "pullTab-light": "bg-white text-gray-20",
}

const paddingSize: Record<PullTabSizeType, string> = {
  mini: "p-0",
  small: "p-2",
  normal: "p-4",
  large: "p-6",
}

const positionShape: Record<PullTabPositionType, string> = {
  left: "rounded-r-lg py-2",
  right: "rounded-l-lg py-2",
  top: "rounded-b-lg px-2",
  bottom: "rounded-t-lg px-2",
}

// --- computed で動的クラスを構築 ---
const variantClasses = computed(() => variantStyles[props.variant ?? "pullTab-primary"])
const paddingClasses = computed(() => paddingSize[props.size ?? "normal"])
const shapeClasses = computed(() => positionShape[props.position])
const shadowClass = computed(() => (props.isShadow ? "shadow-sm shadow-black" : ""))
</script>
